# Generated by Django 2.2.1 on 2019-05-26 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='poblacion',
            name='Ciudad',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='poblacion',
            name='Departamento',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='poblacion',
            name='Latitud',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='poblacion',
            name='Longitud',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='poblacion',
            name='Provincia',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
