# Generated by Django 2.2.1 on 2019-05-26 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0002_auto_20190526_0016'),
    ]

    operations = [
        migrations.AddField(
            model_name='poblacion',
            name='Distrito',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
